### ISSUE TITLE
In Combat with Target attackable triggers together

### ISSUE THREAD

**Issue by Carlosjrlu** [Slothpala/MouseoverActionSettings#10]
It seems that when using the In Combat and Target Attackable trigers together makes any HUD element stay visible after leaving combat with no target selected.

Here is me after leaving combat,
![image](https://github.com/user-attachments/assets/3ba7c327-c0e9-4c68-a385-4c94c2252374)

**Comment by Carlosjrlu** [comment]
Changing the event delay timer to 0 and then back to 2 (default) solved the problem for me. Weird.

**Comment by Slothpala** [comment]
The problem was with the TargetAttackable trigger itself. It was recently added and had a logical flaw. The UnitCanAttack API call works differently than I expected.  It should work as expected now.
