### ISSUE TITLE
The action bar function is not working in ElvUI

### ISSUE THREAD

**Issue by iamhug** [Slothpala/MouseoverActionSettings#13]
I’m using ElvUI, and while the minimap function works well, there is no change with the action bar. Do I need to configure something else?

**Comment by iamhug** [comment]
using Tinker Zone is perfect. thanks

**Comment by Slothpala** [comment]
Yes Tinker Zone is the only option for non Blizzard frames. I am working on a method to export the Tinker Modules as a string.

**Comment by iamhug** [comment]
@Slothpala 
Thank you. I have one more question. Could you provide a sample of the script regions for the Tinker Zone?

I want to control the parent frame when the 'VEHICLE_ACTIONBAR_UPDATE' event occurs."
