### ISSUE TITLE
The display of the Objective Tracker settings under the HUD tab are tied to the "Buff Frame" checkbox instead of the "Objective Tracker" checkbox

### ISSUE THREAD

**Issue by AntoineBnl** [Slothpala/MouseoverActionSettings#3]
This is because the `hidden` function for the ObjectiveTracker entry in HUDtab.lua returns `not addon:IsModuleEnabled("BuffFrame")` instead of `not addon:IsModuleEnabled("ObjectiveTracker")`

**Comment by Slothpala** [comment]
Oh i was a bit to quick there on the copy paste i guess :D thanks! Will update it with the next patch later.

**Comment by Slothpala** [comment]
Fixed with 88fa376ef887f8ee9d280e3008b7e726670f0919
