### ISSUE TITLE
Dominos and MAS

### ISSUE THREAD

**Issue by demines** [Slothpala/MouseoverActionSettings#8]
Addon doesnt work with dominos addon (for action bars) - action bars dont fade away when dominos enabled.

**Comment by Slothpala** [comment]
This add-on is only intended to work on the default UI.

**Comment by Slothpala** [comment]
The problem is that dominoes and bartender have functions to control their own visibility. So I would have to go into the code and hide them when they show the bars. This is just too much work for me. I will rather improve the action bar settings of my addon.
